name: ReVanced + ReVanced Music

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Download YouTube APK
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: 'base'
          fileName: "youtube.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download YouTube Music APKs
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: 'base'
          fileName: "music*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APKs
        run: ./scripts/build.sh -m -r
              
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Generate SHA256 checksums for the signed APK files
        run: ./scripts/sha256gen.sh -m -r
      
      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.date_now_nodashes }}-yt"
          title: "ReVanced ${{ env.date_now }}"
          prerelease: false
          files: |
            build/SHA-256-yt.txt
            build/revanced-nonroot.apk
            vanced-microG.apk

      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced Music
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.date_now_nodashes }}-ytm"
          title: "ReVanced Music ${{ env.date_now }}"
          prerelease: false
          files: |
            build/SHA-256-ytm.txt
            build/revanced-music-nonroot-*.apk
